# Generated by Django 4.2.30 on 2026-05-09 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookExchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("accepted", "Kabul Edildi"),
                            ("rejected", "Reddedildi"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Tamamlandı"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="İstek Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "offered_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offered_in_exchanges",
                        to="books.book",
                        verbose_name="Teklif Edilen Kitap",
                    ),
                ),
                (
                    "requested_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_in_exchanges",
                        to="books.book",
                        verbose_name="İstenen Kitap",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_exchanges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Takas İsteyen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kitap Takası",
                "verbose_name_plural": "Kitap Takasları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(verbose_name="Puan")),
                ("comment", models.TextField(blank=True, verbose_name="Yorum")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Tarih"),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="exchange.bookexchange",
                        verbose_name="İlgili Takas",
                    ),
                ),
                (
                    "giver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_ratings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Puanı Veren",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_ratings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Puanı Alan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Puanlama",
                "verbose_name_plural": "Puanlamalar",
                "unique_together": {("giver", "exchange")},
            },
        ),
    ]
