# Generated by Django 5.2 on 2026-05-12 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Mesaj")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Tarih"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Okundu")),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="exchange.bookexchange",
                        verbose_name="Takas",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gönderen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mesaj",
                "verbose_name_plural": "Mesajlar",
                "ordering": ["created_at"],
            },
        ),
    ]
