# Generated by Django 4.2.30 on 2026-05-09 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Kitap Adı")),
                ("author", models.CharField(max_length=255, verbose_name="Yazar")),
                (
                    "edition",
                    models.PositiveIntegerField(default=1, verbose_name="Baskı"),
                ),
                (
                    "publisher",
                    models.CharField(max_length=255, verbose_name="Yayınevi"),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(verbose_name="Sayfa Sayısı"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Takas Listesinde"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Eklenme Tarihi"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sahip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kitap",
                "verbose_name_plural": "Kitaplar",
                "ordering": ["-created_at"],
            },
        ),
    ]
