# Generated by Django 5.2 on 2026-05-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.CharField(
                choices=[
                    ("roman", "Roman"),
                    ("siir", "Şiir"),
                    ("tarih", "Tarih"),
                    ("bilim", "Bilim"),
                    ("felsefe", "Felsefe"),
                    ("biyografi", "Biyografi"),
                    ("cocuk", "Çocuk"),
                    ("fantastik", "Fantastik"),
                    ("korku", "Korku"),
                    ("dini", "Dini"),
                    ("egitim", "Eğitim"),
                    ("diger", "Diğer"),
                ],
                default="diger",
                max_length=20,
                verbose_name="Tür",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="summary",
            field=models.TextField(blank=True, verbose_name="Özet"),
        ),
    ]
