# Generated by Django 5.2 on 2026-05-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_genre_book_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="book_covers/",
                verbose_name="Kitap Kapağı",
            ),
        ),
    ]
